import Game.Levels.SubgroupWorld.L01_sub_of_ab_is_ab

World "SubgroupWorld"
Level 2
Title "Membership of a subgroup generated from a subset"

namespace MyGroup

/-- defining subgroups generated from a set-/
DefinitionDoc MyGroup.Generated_Subgroup as "Generated Subgroup"

NewDefinition MyGroup.Generated_Subgroup

/-- a subgroup generated from a set contains the identity-/
TheoremDoc MyGroup.Generated_Subgroup.id as "Generated_Subgroup.id"

/-- a subgroup generated from a set contains the elements of the set-/
TheoremDoc MyGroup.Generated_Subgroup.base as "Generated_Subgroup.base"

/-- a subgroup generated from a set contains the inverses of the elements of the set-/
TheoremDoc MyGroup.Generated_Subgroup.inv as "Generated_Subgroup.inv"

/-- a subgroup generated from a set contains the product of two elements of the set-/
TheoremDoc MyGroup.Generated_Subgroup.prod as "Generated_Subgroup.prod"

NewTheorem MyGroup.Generated_Subgroup.id MyGroup.Generated_Subgroup.base
  MyGroup.Generated_Subgroup.inv MyGroup.Generated_Subgroup.prod

/-- matches the current goal against the type of the conclusion of the theorem-/
TacticDoc apply

NewTactic apply

Introduction "TBA"

/-- Let $G$ be a group and $S$ be a subset of the group. Then a member of the set is a member of the subgroup generated by the set.-/
Statement {G : Type _} [Group G] (S : MySet G) (a : G) (ha : a ∈ S) :
  Generated_Subgroup S a := by
    apply Generated_Subgroup.base ha

Conclusion "TBA"
