import Game.Levels.SubgroupWorld.L03_mem_inv_in_subg

World "SubgroupWorld"
Level 4
Title "Membership of elements of a subset multiplied by the identity in the generated subgroup"

namespace MyGroup

Introduction "TBA"

/-- Let $G$ be a group and $S$ a subset of the group. If $a$ is a member of the subset, then $a$ times the identity is in the subgroup generated by $S$.-/
Statement {G : Type _} [Group G] (S : MySet G) (a : G) (ha : a ∈ S) :
  Generated_Subgroup S (a * Identity.id) := by
    have ha_mem := by apply Generated_Subgroup.base ha
    apply Generated_Subgroup.prod ha_mem Generated_Subgroup.id

Conclusion "TBA"
