import Game.Levels.SubgroupWorld.L04_mem_mul_id_in_subg

World "SubgroupWorld"
Level 5
Title "Membership of the product of two elements of a subset in the subgroup generated by it"

namespace MyGroup

Introduction "TBA"

/-- Let $G$ be a group and $S$ a subset of the group. If $a$ and $b$ are in $S$, then $a*b$ is in the subgroup generated by $S$.-/
Statement {G : Type _} [Group G] (S : MySet G) (a b : G) (ha : a ∈ S)
  (hb : b ∈ S) : Generated_Subgroup S (a * b) := by
    have ha_mem := by apply Generated_Subgroup.base ha
    have hb_mem := by apply Generated_Subgroup.base hb
    apply Generated_Subgroup.prod ha_mem hb_mem

Conclusion "TBA"
