import Game.Levels.SubgroupWorld.L05_mem_mul_mem_in_subg

World "SubgroupWorld"
Level 6
Title "The product of an element in a subset and the inverse of another element in the subset is in the subgroup generated by the subset"

namespace MyGroup

Introduction "TBA"

/-- Let $G$ be a group and $S$ a subset of the group. If $a$ and $b$ are in $S$, then $a*b⁻¹$ is in the subgroup generated by $S$.-/
Statement {G : Type _} [Group G] (S : MySet G) (a b : G) (ha : a ∈ S)
  (hb : b ∈ S) : Generated_Subgroup S (a * b⁻¹) := by
    have ha_mem := by apply Generated_Subgroup.base ha
    have hb_mem := by apply Generated_Subgroup.base hb
    have hb_inv := by apply Generated_Subgroup.inv hb_mem
    apply Generated_Subgroup.prod ha_mem hb_inv

Conclusion "TBA"
